
spring:

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
            scope: name,email,avatar_url
          google:
            client-id:
            client-secret:
            scope: profile,email



